services:
  - type: web
    name: hr-backend
    runtime: node
    buildCommand: npm ci && npm run build
    rootDir: .
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
